---
- name: Install Apache in CentOS
  yum:
    name: httpd
    state: latest
  when: 
  - ansible_distribution == "CentOS"

- name: Install Apache in Ubuntu
  apt:
    name: apache2
    state: latest
  when:
  - ansible_distribution == "Ubuntu"

- name: Start Apache in CentOS
  service:
    name: httpd
    state: started
    enabled: yes
  when:
  - ansible_distribution == "CentOS"

- name: Start Apache in Ubuntu
  service:
    name: apache2
    state: started
    enabled: yes
  when:
  - ansible_distribution == "Ubuntu"

- include: mod_index.yml

- name: Transfering httpd.conf
  template:
    src: "{{ httpd_src }}"
    dest: "{{ httpd_dest }}"
  notify:
  - restart apache
  when:
  - ansible_distribution == "CentOS"

- name: Transfering ports.conf
  template:
    src: "{{ ports_src }}"
    dest: "{{ ports_dest }}"
  notify:
  - restart apache
  when:
  - ansible_distribution == "Ubuntu"
