---
- name: Install Apache in CentOS
  yum:
    name: httpd
    state: latest

- name: Start Apache
  service:
    name: httpd
    state: started
    enabled: yes

- include: mod_index.yml

- name: Transfering httpd.conf
  template:
    src: "{{ httpd_src }}"
    dest: "{{ httpd_dest }}"
  notify:
  - restart apache
